version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 70
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 32
  identical-code:
    config:
      threshold: 32
plugins:
  fixme:
    enabled: true
  pep8:
    enabled: true
