version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 20
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 75
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 64
  identical-code:
    config:
      threshold: 64
plugins:
  fixme:
    enabled: true
  pep8:
    enabled: true
