# This a copy of pyprojects.toml for use when building wheels for PyPI
# with cibuildwheel.
#
# The problem: We need to build with specific versions of numpy on each
# version of Python and each platform so that our built wheels work with
# any version of numpy supported by that platform and later than our own
# numpy version requirement. At the same time, we don't want to fix the
# version of numpy in the main pyproject.toml file because that would prevent
# users installing QuTiP with the latest numpy.
#
# See cibuildwheel issue: https://github.com/pypa/cibuildwheel/issues/955
#
# The oldest-support-numpy versions can be found in:
# https://github.com/scipy/oldest-supported-numpy/blob/master/setup.cfg
[build-system]
requires = [
    "setuptools",
    "packaging",
    "wheel",
    "cython>=0.29.20",
    "oldest-supported-numpy",
    "scipy>=1.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
# Change in future version to "build"
build-frontend = "pip"

[tool.cibuildwheel.override]
# NumPy support manylinux2010 on CPython 3.6-3.9
select = "cp3?-*"
manylinux-x86_64-image = "manylinux2010"
manylinux-i686-image = "manylinux2010"
