name: 🚀 Feature Request
description: Suggest an idea for this project!
labels: ["ENH"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Give us a clear and concise description of what the problem is!
      placeholder: "Example - It would be better if [...]"
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Give us a description of your proposed solution
      placeholder: "A clear and concise description of what you want to happen"
    validations:
      required: true
  - type: textarea
    id: alternate-solutions
    attributes:
      label: Alternate Solutions
      description: Are there other ways of implementing this feature?
      placeholder: "A clear and concise description of any alternative solutions or features you've considered"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: You can tell us more about your idea, add code snippets or images, etc.
      placeholder: "Give us more context or screenshots about the feature request here"
  - type: markdown
    id: thank-you
    attributes:
      value: Thanks for taking the time to fill out this feature request!