import numpy as np
import scipy.sparse as sp
import time

from pydiso.mkl_solver import MKLPardisoSolver

def _pardiso_parameters(hermitian, has_perm,
                        max_iter_refine,
                        scaling_vectors,
                        weighted_matching):
    iparm = {
        # 0: 1, # forbidden to set by pydiso
        1: 3,
        **({4: 1} if has_perm else {}),
        7: max_iter_refine,
        **({9: 8} if hermitian else {9: 13}),
        **({10: int(scaling_vectors)} if not hermitian else {}),
        **({12: int(weighted_matching)} if not hermitian else {}),
        17: -1, 
        20: 1,
        23: 1,
        26: 0,
        34: 1
        }
    # iparm = np.zeros(64, dtype=np.int32)
    # iparm[0] = 1  # Do not use default values
    # iparm[1] = 3  # Use openmp nested dissection
    # if has_perm:
    #     iparm[4] = 1
    # iparm[7] = max_iter_refine  # Max number of iterative refinements
    # if hermitian:
    #     iparm[9] = 8
    # else:
    #     iparm[9] = 13
    # if not hermitian:
    #     iparm[10] = int(scaling_vectors)
    #     iparm[12] = int(weighted_matching)  # Non-symmetric weighted matching
    # iparm[17] = -1
    # iparm[20] = 1
    # iparm[23] = 1  # Parallel factorization
    # iparm[26] = 0  # Check matrix structure
    # iparm[34] = 1  # Use zero-based indexing
    return iparm

# TODO: Hermitian is set to 1 in qutip/tests/test_mkl.py, so there are no tests for nonsymmetric matrices (i.e., the path where the upper triangular matrix is taken is not tested)

def _default_solver_args():
    return {
        'hermitian': False,
        'posdef': False,
        'has_perm': False,
        'max_iter_refine': 10,
        'scaling_vectors': True,
        'weighted_matching': True,
        'return_info': False,
    }


class mkl_lu:
    """
    Object pointing to LU factorization of a sparse matrix
    generated by mkl_splu.
    
    Parameters
    ----------
    solver : pydiso.mkl_solver.MKLPardisoSolver
    mtype : str
    data_type : 
    factor_time :

    Methods
    -------
    solve(b, verbose=False)
        Solve system of equations using given RHS vector 'b'.
        Returns solution ndarray with same shape as input.

    info()
        Returns the statistics of the factorization and
        solution in the lu.info attribute.

    delete()
        Deletes the allocated solver memory.

    """
    def __init__(self, solver, mtype, data_type, factor_time):
        self._solver = solver
        self._mtype = mtype
        self._data_type = data_type
        self._is_complex = np.issubdtype(data_type, np.complexfloating)
        self._factor_time = factor_time
        self._solve_time = None
        self._info = None

    def solve(self, b, verbose=None):
        if self._solver is None:
            raise RuntimeError("Solver's memory has been released. Initialise mkl_lu again.")

        if sp.issparse(b):
            raise TypeError(
                "Right-hand side must be dense. Use mkl_spsolve for a sparse b"
                "instead of using mkl_lu.solve directly"
            )
        b = np.asarray(b)

        if np.issubdtype(b.dtype, np.complexfloating) and not self._is_complex:
            raise TypeError(
                "Got a complex right-hand side: cannot solve real-valued factorization"
            )

        if b.dtype != self._data_type:
            # Pydiso wrapper would do the conversion and throw a warning;
            # hence, we do data type conversion in advance
            b = b.astype(self._data_type)

        _solve_start = time.time()
        x = self._solver.solve(b)
        self._solve_time = time.time() - _solve_start
        return x

    def info(self):
        if self._solver is None:
            return self._info
        iparm = self._solver.iparm
        return {'FactorTime': self._factor_time,
                'SolveTime': self._solve_time,
                'Factormem': round(iparm[15]/1024, 4),
                'Solvemem': round(iparm[16]/1024, 4),
                'IterRefine': iparm[6]}

    def delete(self):
        # Preserve the info before memory deallocation for solver
        self._info = self.info()
        self._solver = None


_MATRIX_TYPE_NAMES = {
    4: 'Complex Hermitian positive-definite',
    -4: 'Complex Hermitian indefinite',
    2: 'Real symmetric positive-definite',
    -2: 'Real symmetric indefinite',
    11: 'Real non-symmetric',
    13: 'Complex non-symmetric',
}


def _mkl_matrix_type(dtype, solver_args):
    is_complex = np.issubdtype(dtype, np.complexfloating)
    if not solver_args['hermitian']:
        return 13 if is_complex else 11
    out = 4 if is_complex else 2
    return out if solver_args['posdef'] else -out

# Returns factorisation object: important for tests
def mkl_splu(A,
             perm=None,
             verbose=False,
             *,
             hermitian=False,
             posdef=False,
             max_iter_refine=10,
             scaling_vectors=True,
             weighted_matching=True,
        )
    """
    Returns the LU factorization of the sparse matrix A.

    Parameters
    ----------
    A : csr_matrix
        Sparse input matrix.
    perm : ndarray (optional)
        User defined matrix factorization permutation.
    verbose : bool {False, True}
        Report factorization details.

    Returns
    -------
    lu : mkl_lu
        Returns object containing LU factorization with a
        solve method for solving with a given RHS vector.

    """
    if not (sp.issparse(A) and A.format == "csr"):
        raise TypeError('Input matrix must be in sparse CSR format.')

    if A.shape[0] != A.shape[1]:
        raise Exception('Input matrix must be square')

    solver_args = _default_solver_args()
    left_over_args = set(kwargs) - set(solver_args)
    if left_over_args:
        raise ValueError(
            f"Unknown keyword arguments pass to mkl_splu: {left_over_args}"
        )
    solver_args.update(kwargs)

    if not np.issubdtype(A.dtype, np.inexact):
        A = sp.csr_matrix(A, dtype=np.float64, copy=False)

    data_type = A.dtype

    mtype = _mkl_matrix_type(data_type, solver_args) # TODO: wrapper also supports complex64/float64, we should adapt the matrix type inference
    
    # TODO: evaluate pydiso's logging capabilities: what is there and what we should add
    if verbose:
        print('Solver Initialization')
        print('---------------------')
        print('Input matrix type: ', _MATRIX_TYPE_NAMES[mtype])
        print('Input matrix shape:', A.shape)
        print('Input matrix NNZ:  ', A.nnz)
        print()

    # Call solver # TODO: here, we will call the solver
    _factor_start = time.time()
    solver_args.pop("posdef")
    solver_args.pop("return_info")
    iparms = _pardiso_parameters(**solver_args)
    solver = MKLPardisoSolver(A, matrix_type=mtype, iparm_overrides=iparms)
    # TODO: Check if the class handles same iparm's by default to avoid redundant set_iparm calls
    # TODO: we cannot set iparm before analysis and factorisation - the setter performs it after those steps;
    # we should find a way to pass 1/10/12/23 upon initialisation
    solver.set_iparm(7, solver_args['max_iter_refine'])
    _factor_time = time.time() - _factor_start
    # TODO: iparm must be taken from solve
    if verbose:
        print('Analysis and Factorization Stage')
        print('--------------------------------')
        print('Factorization time:       ', round(_factor_time, 4))
        print('Factorization memory (Mb):', round(solver.iparm[15]/1024, 4))
        print('NNZ in LU factors:        ', solver.iparm[17])
        print()
    return mkl_lu(solver, mtype, data_type, _factor_time)

# TODO: issue: we cannot use perm parameter with pydiso solver
def mkl_spsolve(A, b, perm=None, verbose=False, **kwargs):
    """
    Solves a sparse linear system of equations using the
    Intel MKL Pardiso solver.

    Parameters
    ----------
    A : csr_matrix
        Sparse matrix.
    b : ndarray or sparse matrix
        The vector or matrix representing the right hand side of the equation. If a vector, b.shape must be (n,) or (n, 1).
    perm : ndarray (optional)
        User defined matrix factorization permutation.

    Returns
    -------
    x : ndarray or csr_matrix
        The solution of the sparse linear equation.
        If b is a vector, then x is a vector of size A.shape[1]
        If b is a matrix, then x is a matrix of size (A.shape[1], b.shape[1])

    """
    A = sp.csr_matrix(A)
    lu = mkl_splu(A, perm=perm, verbose=verbose, **kwargs)
    try:
        return_sparse = sp.issparse(b) and b.ndim == 2 and b.shape[1] != 1
        if sp.issparse(b):
            # qutip's convention: a sparse RHS of shape (n, 1) produces dense solution
            b = b.toarray()
        x = lu.solve(b, verbose=verbose)
        if return_sparse:
            x = sp.csr_matrix(x)

        info = lu.info()
    finally:
        lu.delete()
    return (x, info) if kwargs.get('return_info', False) else x
