import numpy as np
import scipy.sparse as sp
import time

from pydiso.mkl_solver import MKLPardisoSolver

# dev note: after migration to pydiso (#...), using user-supplied permutations is not possible
# TODO: add proper explanation of overrides w.r.t. Intel's pardiso iparm Parameter reference
def _iparm_overrides(
                *,
                hermitian,
                max_iter_refine,
                scaling_vectors,
                weighted_matching):
    # Get QuTiP-defined iparms
    overrides = {
        1: 3,
        7: max_iter_refine,
        23: 1,
        26: 0,
    }

    # Note: {0: 1} is forbidden to set by pydiso
    # Add extra arguments in case of non-Hermitian matrix type
    if not hermitian:
        overrides |= {
                10: int(scaling_vectors),
                12: int(weighted_matching),
            }
    # iparm = np.zeros(64, dtype=np.int32)
    # iparm[0] = 1  # Do not use default values
    # iparm[1] = 3  # Use openmp nested dissection
    # if has_perm:
    #     iparm[4] = 1
    # iparm[7] = max_iter_refine  # Max number of iterative refinements
    # if hermitian:
    #     iparm[9] = 8
    # else:
    #     iparm[9] = 13
    # if not hermitian:
    #     iparm[10] = int(scaling_vectors)
    #     iparm[12] = int(weighted_matching)  # Non-symmetric weighted matching
    # iparm[17] = -1
    # iparm[20] = 1
    # iparm[23] = 1  # Parallel factorization
    # iparm[26] = 0  # Check matrix structure
    # iparm[34] = 1  # Use zero-based indexing
    return overrides

# TODO: Hermitian is set to 1 in qutip/tests/test_mkl.py, so there are no tests for nonsymmetric matrices (i.e., the path where the upper triangular matrix is taken is not tested)


class MKLFactorization:
    """
    Object pointing to LU factorization of a sparse matrix
    generated by mkl_splu.
    
    Parameters
    ----------
    solver : pydiso.mkl_solver.MKLPardisoSolver
    mtype : str
    data_type : 
    factor_time :

    Methods
    -------
    solve(b, verbose=False)
        Solve system of equations using given RHS vector 'b'.
        Returns solution ndarray with same shape as input.

    info()
        Returns the statistics of the factorization and
        solution in the lu.info attribute.

    delete()
        Deletes the allocated solver memory.

    """
    def __init__(self, solver, mtype, data_type, factor_time):
        self._solver = solver
        self._mtype = mtype
        self._data_type = data_type
        self._is_complex = np.issubdtype(data_type, np.complexfloating)
        self._factor_time = factor_time
        self._solve_time = None
        self._info = None

    def solve(self, b, verbose=False):
        if self._solver is None:
            raise RuntimeError("Solver's memory has been released. Initialise MKLFactorization again.")

        if sp.issparse(b):
            raise TypeError(
                "Right-hand side must be dense. Use mkl_spsolve for a sparse b"
                "instead of using MKLFactorization.solve directly"
            )
        b = np.asarray(b)

        if np.issubdtype(b.dtype, np.complexfloating) and not self._is_complex:
            raise TypeError(
                "Got a complex right-hand side: cannot solve real-valued factorization"
            )

        if b.dtype != self._data_type:
            # Pydiso wrapper would do the conversion and throw a warning;
            # hence, we do data type conversion in advance
            b = b.astype(self._data_type)

        _solve_start = time.perf_counter()
        x = self._solver.solve(b)
        self._solve_time = time.perf_counter() - _solve_start
        return x

    def info(self):
        if self._solver is None:
            return self._info
        iparm = self._solver.iparm
        return {'FactorTime': self._factor_time,
                'SolveTime': self._solve_time,
                'Factormem': round(iparm[15]/1024, 4),
                'Solvemem': round(iparm[16]/1024, 4),
                'IterRefine': iparm[6]}

    def delete(self):
        # Preserve the info before memory deallocation for solver
        self._info = self.info()
        self._solver = None


_MATRIX_TYPE_NAMES = {
    4: 'Complex Hermitian positive-definite',
    -4: 'Complex Hermitian indefinite',
    2: 'Real symmetric positive-definite',
    -2: 'Real symmetric indefinite',
    11: 'Real non-symmetric',
    13: 'Complex non-symmetric',
}


def _mkl_matrix_type(dtype, hermitian, posdef):
    is_complex = np.issubdtype(dtype, np.complexfloating)
    if not hermitian:
        return 13 if is_complex else 11
    out = 4 if is_complex else 2
    return out if posdef else -out

# Returns factorisation object: important for tests
def mkl_splu(A,
             perm=None,
             verbose=False,
             *,
             hermitian=False,
             posdef=False,
             max_iter_refine=10,
             scaling_vectors=True,
             weighted_matching=True,
             ):
    """
    Returns the LU factorization of the sparse matrix A.

    Parameters
    ----------
    A : csr_matrix
        Sparse input matrix.
    perm : ndarray (optional)
        User defined matrix factorization permutation.
    verbose : bool {False, True}
        Report factorization details.

    Returns
    -------
    lu : MKLFactorization
        Returns object containing LU factorization with a
        solve method for solving with a given RHS vector.

    """
    if not (sp.issparse(A) and A.format == "csr"):
        raise TypeError('Input matrix must be in sparse CSR format.')

    if A.shape[0] != A.shape[1]:
        raise Exception('Input matrix must be square')

    if not np.issubdtype(A.dtype, np.inexact):
        A = sp.csr_matrix(A, dtype=np.float64, copy=False)

    data_type = A.dtype

    mtype = _mkl_matrix_type(data_type, hermitian, posdef)
    
    # TODO: evaluate pydiso's logging capabilities: what is there and what we should add
    # if verbose:
    #     print('Solver Initialization')
    #     print('---------------------')
    #     print('Input matrix type: ', _MATRIX_TYPE_NAMES[mtype])
    #     print('Input matrix shape:', A.shape)
    #     print('Input matrix NNZ:  ', A.nnz)
    #     print()
    if perm is not None:
        raise NotImplementedError("User-defined permutations are not supported by the pydiso backend.")
    # Call solver # TODO: here, we will call the solver
    _factor_start = time.perf_counter()
    iparms = _iparm_overrides(hermitian=hermitian, max_iter_refine=max_iter_refine,
                                 scaling_vectors=scaling_vectors,
                                 weighted_matching=weighted_matching)
    solver = MKLPardisoSolver(A, matrix_type=mtype, verbose=verbose, iparm_overrides=iparms)
    _factor_time = time.perf_counter() - _factor_start
    # if verbose:
    #     print('Analysis and Factorization Stage')
    #     print('--------------------------------')
    #     print('Factorization time:       ', round(_factor_time, 4))
    #     print('Factorization memory (Mb):', round(solver.iparm[15]/1024, 4))
    #     print('NNZ in LU factors:        ', solver.iparm[17])
    #     print()
    return MKLFactorization(solver, mtype, data_type, _factor_time)

# TODO: issue: we cannot use perm parameter with pydiso solver
def mkl_spsolve(A,
                b,
                perm=None,
                verbose=False,
                *,
                return_info=False,
                hermitian=False,
                posdef=False,
                max_iter_refine=10,
                scaling_vectors=True,
                weighted_matching=True,
        ):
    """
    Solves a sparse linear system of equations using the
    Intel MKL Pardiso solver.

    Parameters
    ----------
    A : csr_matrix
        Sparse matrix.
    b : ndarray or sparse matrix
        The vector or matrix representing the right hand side of the equation. If a vector, b.shape must be (n,) or (n, 1).
    perm : ndarray (optional)
        User defined matrix factorization permutation.

    Returns
    -------
    x : ndarray or csr_matrix
        The solution of the sparse linear equation.
        If b is a vector, then x is a vector of size A.shape[1]
        If b is a matrix, then x is a matrix of size (A.shape[1], b.shape[1])

    """
    A = sp.csr_matrix(A)
    lu = mkl_splu(A, perm=perm, verbose=verbose, hermitian=hermitian, posdef=posdef, max_iter_refine=max_iter_refine, scaling_vectors=scaling_vectors, weighted_matching=weighted_matching)
    try:
        return_sparse = sp.issparse(b) and b.ndim == 2 and b.shape[1] != 1
        if sp.issparse(b):
            # qutip's convention: a sparse RHS of shape (n, 1) produces dense solution
            b = b.toarray(order="F")
        x = lu.solve(b, verbose=verbose)
        if return_sparse:
            x = sp.csr_matrix(x)

        info = lu.info()
    finally:
        lu.delete()
    return (x, info) if return_info else x
