
class QasmOutput():
    def __init__(self, version="2.0"):
        self.version = version
        self.lines = []

    def output(self, line="", n=0):
        if line:
            self.lines.append(line)
        self.lines = self.lines + [""] * n

    def _output_qasm(self, qc):

        self.output("// QASM 2.0 file generated by QuTiP", 1)

        if self.version == "2.0":
            self.output("OPENQASM 2.0;", 2)
        else:
            raise NotImplementedError("Only version 2.0 is supported for now")

        self.output('include "qelib1.inc";', 1)

        qc._qasm_output(self.output)

    def print_qasm(self, qc):

        self._output_qasm(qc)
        for line in self.lines:
            print(line)


    def save_qasm(self, qc, file_loc):

        self._output_qasm(qc, gate_def_file)
        with open(file_loc, "w") as f:
            f.writelines(self.lines)
