#!/usr/bin/env python3
"""Git hash suffix for dev builds e.g. 5.4.0.dev0+g1a2b3c4."""
import pathlib
import subprocess
import sys

root = pathlib.Path(__file__).resolve().parent.parent
version = (root / "VERSION").read_text().strip()

if "dev" in version:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--verify", "--short=7", "HEAD"],
            check=True, capture_output=True, cwd=root,
        )
        version += "+" + out.stdout.decode().strip()
    except (subprocess.CalledProcessError, OSError):
        pass

if "--write" in sys.argv:
    # Attributes must match the qutip/version.pyi stub.
    target = root / "qutip" / "version.py"
    content = (
        "# This file is automatically generated by tools/git-versioning.py.\n"
        f"short_version = {version.split('+')[0]!r}\n"
        f"version = {version!r}\n"
        f"release = {'dev' not in version!r}\n"
    )
    if not target.exists() or target.read_text() != content:
        target.write_text(content)

print(version)