name: Build wheels, optionally deploy to PyPI
permissions:
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      confirm_ref:
        description: "Confirm chosen branch name to deploy to PyPI (optional):"
        default: ""
      override_version:
        description: "Override version number (optional):"
        default: ""


jobs:
  # The deploy_test job is part of the test of whether we should deploy to PyPI
  # or test.PyPI. The job will succeed if either the confirmation reference is
  # empty, 'test' or if the confirmation is the selected branch or tag name.
  # It will fail if it is nonempty and does not match.  All later jobs depend
  # on this job, so that they will be immediately cancelled if the confirmation
  # is bad.  The dependency is currently necessary (2021-03) because GitHub
  # Actions does not have a simpler method of cancelling an entire workflow---
  # the normal use-case expects to try and run as much as possible despite one
  # or two failures.
  deploy_test:
    name: Verify PyPI deployment confirmation
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.mode.outputs.mode }}
    env:
      CONFIRM_REF: ${{ github.event.inputs.confirm_ref }}
    steps:
      - name: Set confirmation is triggered by tag
        if: github.event_name == 'release'
        # TODO: set to the version when working.
        run: echo "CONFIRM_REF=test" >> "$GITHUB_ENV"
        # run: echo "CONFIRM_REF=$GITHUB_REF_NAME" >> "$GITHUB_ENV"

      - name: Compare confirmation to current reference
        id: mode
        shell: bash
        run: |
          if ! [[ -z $CONFIRM_REF || $CONFIRM_REF == "test" || $GITHUB_REF_NAME == "$CONFIRM_REF" ]]; then
            echo "::error::confirm_ref '$CONFIRM_REF' does not match '$GITHUB_REF_NAME', 'test' or ''"
            exit 1
          fi
          if [[ $CONFIRM_REF == "test" ]]; then
            echo "Build and deploy to test.pypi.org."
            mode=testpypi
          elif [[ -z $CONFIRM_REF ]]; then
            echo "Build only.  Nothing will be uploaded to PyPI."
            mode=none
          else
            echo "Full build and deploy.  Wheels and source will be uploaded to PyPI."
            mode=pypi
          fi
          echo "mode=$mode" >> "$GITHUB_OUTPUT"


  build_sdist:
    name: Build sdist on Ubuntu
    needs: deploy_test
    runs-on: ubuntu-latest
    env:
      OVERRIDE_VERSION: ${{ github.event.inputs.override_version }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        name: Install Python
        with:
          # For the sdist we should be as conservative as possible with our
          # Python version.  This should be the lowest supported version.  This
          # means that no unsupported syntax can sneak through.
          python-version: '3.11'

      - name: Install pip build
        run: |
          python -m pip install 'build'

      - name: Build sdist tarball
        shell: bash
        run: |
          if [[ ! -z "$OVERRIDE_VERSION" ]]; then echo "$OVERRIDE_VERSION" > VERSION; fi
          # The build package is the reference PEP 517 package builder.  All
          # dependencies are specified by our setup code.
          python -m build --sdist .

      # Zip files are not part of PEP 517, so we need to make our own.
      - name: Create zipfile from tarball
        shell: bash
        working-directory: dist
        run: |
          # First assert that there is exactly one tarball, and find its name.
          shopt -s failglob
          tarball_pattern="*.tar.gz"
          tarballs=($tarball_pattern)
          [[ ${#tarballs[@]} == 1 ]]
          tarball="${tarballs[0]}"
          # Get the stem and make the zipfile name.
          stem="${tarball%.tar.gz}"
          zipfile="${stem}.zip"
          # Extract the tarball and rezip it.
          tar -xzf "$tarball"
          zip "$zipfile" -r "$stem"
          rm -r "$stem"

      - uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: |
            dist/*.tar.gz
            dist/*.zip
          if-no-files-found: error


  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: deploy_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Each os has two instruction set (x86, arm) that needs different build.
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      # Set up wheels matrix.  This is CPython 3.11--3.14 for all OS targets.
      CIBW_BUILD: "cp3{11,12,13,14}-*"
      # Numpy and SciPy do not supply wheels for i686 or win32 for
      # Python 3.10+, so we skip those:
      CIBW_SKIP: "*-musllinux* *-manylinux_i686 *-win32"
      # Force recent version of manylinux
      OVERRIDE_VERSION: ${{ github.event.inputs.override_version }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        name: Install Python
        with:
          # This is about the build environment, not the released wheel version.
          python-version: '3.11'

      - name: Install cibuildwheel
        run: |
          # cibuildwheel does the heavy lifting for us. >=3 is needed for
          # python 3.14.
          python -m pip install 'cibuildwheel==3.3.*'

      - name: Build wheels
        shell: bash
        run: |
          # If the version override was specified, then write it the VERSION
          # file with it.
          if [[ ! -z "$OVERRIDE_VERSION" ]]; then echo "$OVERRIDE_VERSION" > VERSION; fi
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl


  check_build:
    name: "Check built wheels"
    needs: [deploy_test, build_sdist, build_wheels]
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts to local runner
        uses: actions/download-artifact@v8
        with:
          path: wheels
          merge-multiple: true

      # Check that all .whl, .tar.gz and .zip have been properly build
      # and downloaded.
      - name: Check wheels
        run: |
          ls -R wheels
          if ! [[ $(ls wheels/*.whl | wc -l) == 24 ]]; then exit 1; fi
          if ! ls wheels/*.tar.gz 1> /dev/null 2>&1; then exit 1; fi
          if ! ls wheels/*.zip 1> /dev/null 2>&1; then exit 1; fi

      - uses: actions/setup-python@v7
        name: Install Python
        with:
          python-version: '3.14'

      - name: Verify this is not a dev version
        shell: bash
        run: |
          python -m pip install wheels/*-cp314-cp314-manylinux*_x86_64.whl
          python -c 'import qutip; print(qutip.__version__); assert "dev" not in qutip.__version__; assert "+" not in qutip.__version__'


  deploy_pypi:
    name: "Deploy to PyPI if desired"
    needs: [deploy_test, check_build]
    if: needs.deploy_test.outputs.mode == 'pypi' && github.repository == 'qutip/qutip'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/qutip

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheels
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels/
          verbose: true


  deploy_testpypi:
    name: "Deploy to TestPyPI if desired"
    needs: [deploy_test, check_build]
    if: needs.deploy_test.outputs.mode == 'testpypi' && github.repository == 'qutip/qutip'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/qutip

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheels
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: wheels/
          skip-existing: true
          verbose: true


  github-release:
    name: >-
      Sign the qutip with Sigstore and upload them to GitHub Release
    needs:
    - deploy_pypi
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download build artifacts to local runner
        uses: actions/download-artifact@v8
        with:
          path: wheels
          merge-multiple: true

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.4.0
        with:
          inputs: ./wheels/*.tar.gz ./wheels/*.whl
          release-signing-artifacts: false
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload "$GITHUB_REF_NAME" wheels/** --repo "$GITHUB_REPOSITORY"
