name: Test family projects
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version, empty for development, `release` for latest released version'
        default: ""

  pull_request:

defaults:
  run:
    # The slightly odd shell call is to force bash to read .bashrc, which is
    # necessary for having conda behave sensibly.
    shell: bash -l -e {0}

jobs:
  tests:
    name: ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [qutip-qip, qutip-jax, qutip-qoc, qutip-qtrl]

    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install QuTiP and dependencies
        run: |
          python -m pip install .[runtime_compilation] --group tests -v

      - name: Pre-install development dependencies
        if: ${{ matrix.repo == 'qutip-qoc' }}
        run: |
          cd ..
          git clone https://github.com/qutip/qutip-jax.git
          cd qutip-jax
          if [[ "${{ inputs.version }}" == "release" ]]; then
            # Checkout the latest tag as the latest release
            git fetch --tags
            git checkout $(git describe --tags "$(git rev-list --tags --max-count=1)")
          fi
          python -m pip install . --no-build-isolation

      - name: Install QuTiP family package
        run: |
          cd ..
          git clone https://github.com/qutip/${{ matrix.repo }}.git
          cd ${{ matrix.repo }}
          if [[ "${{ inputs.version }}" == "release" ]]; then
            # Checkout the latest tag as the latest release
            git fetch --tags
            git checkout $(git describe --tags "$(git rev-list --tags --max-count=1)")
          elif [[ "${{ inputs.version }}" ]]; then
            git checkout ${{ inputs.version }}
          fi
          python -m pip install .[full] --no-build-isolation --upgrade-strategy only-if-needed

      - name: Print python environment
        run: |
          pip list

      - name: Run test
        run: |
          cd ../${{ matrix.repo }}
          pytest tests -vv -W "ignore::DeprecationWarning"

  tutorials:
    name: qutip-tutorials, python${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.12"
            no-conda: false

    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        if: ${{ !matrix.no-conda }}
        with:
          miniforge-version: latest
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-remove-defaults: "true"

      - uses: actions/setup-python@v7
        if: ${{ matrix.no-conda }}
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Checkout qutip-tutorials
        run: |
          cd ..
          git clone https://github.com/qutip/qutip-tutorials.git

      - name: Install tutorial environment with Conda
        if: ${{ !matrix.no-conda }}
        run: |
          conda install -y \
            "pip>=22.1.2" \
            "numpy>=2.0.0" \
            "scipy>=1.9" \
            "matplotlib>=3.9" \
            "imagemagick>=7.1.0_36" \
            "mpmath>=1.2.1" \
            "pytest>=7.1.2" \
            "nbmake>=1.3.4" \
            "jupytext>=1.13.8" \
            "jupyter>=1.0.0" \
            "ipykernel>=6.17.1" \
            "cython>=0.29.20"

      - name: Install tutorial environment with pip
        if: ${{ matrix.no-conda }}
        run: |
          python -m pip install --upgrade \
            "pip>=22.1.2" \
            "numpy>=2.0.0" \
            "scipy>=1.9" \
            "matplotlib>=3.9" \
            "mpmath>=1.2.1" \
            "pytest>=7.1.2" \
            "nbmake>=1.3.4" \
            "jupytext>=1.13.8" \
            "jupyter>=1.0.0" \
            "ipykernel>=6.17.1" \
            "cython>=0.29.20"

      - name: Install QuTiP from this checkout
        run: |
          python -m pip install '.[runtime_compilation]'

      - name: Install JAX dependencies
        if: ${{ !matrix.no-conda }}
        run: |
          python -m pip install "jax<0.7.0" "jax[cpu]<0.7.0" equinox diffrax

      - name: Install JAX dependencies for pre-release Python
        if: ${{ matrix.no-conda }}
        run: |
          # Old jaxlib releases do not provide Python pre-release wheels.
          python -m pip install "jax[cpu]" equinox diffrax

      - name: Install tutorial family packages
        run: |
          python -m pip install qutip-qip
          python -m pip install --no-deps git+https://github.com/qutip/qutip-jax
          python -m pip install --no-deps git+https://github.com/qutip/qutip-qtrl
          python -m pip install --no-deps git+https://github.com/qutip/qutip-qoc

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick texlive-latex-extra

      - name: Convert v5 tutorials to notebooks
        run: |
          cd ../qutip-tutorials
          mkdir notebooks
          cp -r tutorials-v5/* notebooks
          cd notebooks
          find . -name '*.md' -exec jupytext --to notebook {} +
          find . -name '*.md' -delete
          # This notebook requires a CUDA-capable runner.
          rm miscellaneous/cuQuantum_backend.ipynb

      - name: Run tutorial notebooks
        run: |
          cd ../qutip-tutorials/notebooks
          find . -name '*.ipynb' -exec pytest --nbmake --nbmake-timeout=900 {} +
