name: Test family projects
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version, empty for development, `release` for latest released version'
        default: ""

  pull_request:

defaults:
  run:
    # The slightly odd shell call is to force bash to read .bashrc, which is
    # necessary for having conda behave sensibly.
    shell: bash -l -e {0}

jobs:
  tests:
    name: ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [qutip-qip, qutip-jax, qutip-qoc, qutip-qtrl]

    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install QuTiP and dependencies
        run: |
          python -m pip install .[runtime_compilation] --group tests -v

      - name: Pre-install development dependencies
        if: ${{ matrix.repo == 'qutip-qoc' }}
        run: |
          cd ..
          git clone https://github.com/qutip/qutip-jax.git
          cd qutip-jax
          if [[ "${{ inputs.version }}" == "release" ]]; then
            # Checkout the latest tag as the latest release
            git fetch --tags
            git checkout $(git describe --tags "$(git rev-list --tags --max-count=1)")
          fi
          python -m pip install . --no-build-isolation

      - name: Install QuTiP family package
        run: |
          cd ..
          git clone https://github.com/qutip/${{ matrix.repo }}.git
          cd ${{ matrix.repo }}
          if [[ "${{ inputs.version }}" == "release" ]]; then
            # Checkout the latest tag as the latest release
            git fetch --tags
            git checkout $(git describe --tags "$(git rev-list --tags --max-count=1)")
          elif [[ "${{ inputs.version }}" ]]; then
            git checkout ${{ inputs.version }}
          fi
          python -m pip install .[full] --no-build-isolation --upgrade-strategy only-if-needed

      - name: Print python environment
        run: |
          pip list

      - name: Run test
        run: |
          cd ../${{ matrix.repo }}
          pytest tests -vv -W "ignore::DeprecationWarning"

  tutorials:
    name: qutip-tutorials
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          activate-environment: test
          python-version: 3.15.0rc2
          channels: conda-forge
          conda-remove-defaults: "true"

      - name: Checkout qutip-tutorials
        run: |
          cd ..
          git clone https://github.com/qutip/qutip-tutorials.git

      - name: Install tutorial dependencies
        run: |
          conda env update -n test -f ../qutip-tutorials/test_environment-v5.yml
          python -m pip install "jax<0.7.0" "jax[cpu]<0.7.0" equinox diffrax
          python -m pip install qutip-qip
          python -m pip install --no-deps git+https://github.com/qutip/qutip-jax
          python -m pip install --no-deps git+https://github.com/qutip/qutip-qtrl
          python -m pip install --no-deps git+https://github.com/qutip/qutip-qoc

      - name: Install QuTiP from this checkout
        run: |
          python -m pip install '.[runtime_compilation]'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg texlive-latex-extra

      - name: Convert v5 tutorials to notebooks
        run: |
          cd ../qutip-tutorials
          mkdir notebooks
          cp -r tutorials-v5/* notebooks
          cd notebooks
          find . -name '*.md' -exec jupytext --to notebook {} +
          find . -name '*.md' -delete
          # This notebook requires a CUDA-capable runner.
          rm miscellaneous/cuQuantum_backend.ipynb

      - name: Run tutorial notebooks
        run: |
          cd ../qutip-tutorials/notebooks
          find . -name '*.ipynb' -exec pytest --nbmake --nbmake-timeout=900 {} +
